spring:
  jpa:
    show-sql: false
  
  flyway:
    enabled: true

logging:
  level:
    root: WARN
    com.cbap: INFO

cbap:
  node:
    mode: REGISTERED
  
  cors:
    allowed-origins:
      - ${FRONTEND_ORIGIN:https://your-frontend-domain.com}
